version: '3.9'
services:
  chat-service:
    build: ./services/chat-service
    ports:
      - "3000:3000"
    volumes:
      - ./services/chat-service:/app
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    # volumes:
    #   - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - chat-network


networks:
  chat-network:
    name: chat-network
    driver: bridge